[project]
name = "ggs_social_api"
version = "1.0.0"
description = "API for GGS Social"
dependencies = [
    "flask",
    "python-dotenv",
    "bcrypt"
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"